<?php

namespace ContainerDJLgvcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RatingFormType' shared autowired service.
     *
     * @return \App\Form\RatingFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RatingFormType.php';

        return $container->privates['App\\Form\\RatingFormType'] = new \App\Form\RatingFormType();
    }
}
