nelmio_api_doc:
    documentation:
        info:
            title: MoviesApi
            description: This is a example api to storage movies
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns: # an array of regexps (document only routes under /api, expect /api/doc)
            - ^/api(?!/doc$)
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.