<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDJLgvcy\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDJLgvcy/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDJLgvcy.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDJLgvcy\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDJLgvcy\App_KernelProdContainer([
    'container.build_hash' => 'DJLgvcy',
    'container.build_id' => 'a2675bf4',
    'container.build_time' => 1657248702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDJLgvcy');
