<?php

namespace ContainerA3rXPsa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_Security_Guard_JwtTokenAuthenticatorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'lexik_jwt_authentication.security.guard.jwt_token_authenticator' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator
     *
     * @deprecated Since lexik/jwt-authentication-bundle 2.7: The "lexik_jwt_authentication.security.guard.jwt_token_authenticator" service is deprecated and will be removed in 3.0, use the new "jwt" authenticator instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('lexik/jwt-authentication-bundle', '2.7', 'The "lexik_jwt_authentication.security.guard.jwt_token_authenticator" service is deprecated and will be removed in 3.0, use the new "jwt" authenticator instead.');

        return $container->privates['lexik_jwt_authentication.security.guard.jwt_token_authenticator'] = new \Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator(($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['lexik_jwt_authentication.extractor.chain_extractor'] ?? $container->load('getLexikJwtAuthentication_Extractor_ChainExtractorService')), new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage(), NULL);
    }
}
