<?php

namespace ContainerA3rXPsa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\MovieService' shared autowired service.
     *
     * @return \App\Service\MovieService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BaseService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MovieService.php';

        return $container->privates['App\\Service\\MovieService'] = new \App\Service\MovieService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
