<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'movie_save' => [[], ['_controller' => 'App\\Controller\\MovieController::new'], [], [['text', '/api/v1/movies']], [], [], []],
    'movie_get_one' => [['id'], ['_controller' => 'App\\Controller\\MovieController::getById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/movies']], [], [], []],
    'movie_get_all' => [[], ['_controller' => 'App\\Controller\\MovieController::getAll'], [], [['text', '/api/v1/movies']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/register']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'authentication_token' => [[], [], [], [['text', '/authentication_token']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
];
