<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTKgbzkI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTKgbzkI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTKgbzkI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTKgbzkI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTKgbzkI\App_KernelDevDebugContainer([
    'container.build_hash' => 'TKgbzkI',
    'container.build_id' => 'fa8d0bcc',
    'container.build_time' => 1657291295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTKgbzkI');
