<?php

namespace ContainerTKgbzkI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_ExceptionListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'app.exception_listener' shared autowired service.
     *
     * @return \App\EventListeners\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListeners/ExceptionListener.php';

        return $container->privates['app.exception_listener'] = new \App\EventListeners\ExceptionListener(($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), false);
    }
}
